language: generic
sudo: required
services:
  - docker
branches:
  only:
    - main

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -f ./client/Dockerfile.dev -t ekpo3/complex-client ./client

script:
  - docker run -e CI=true ekpo3/complex-client npm run test

after_success:
  - docker build -t ekpo3/complex-client ./client
  - docker build -t ekpo3/complex-nginx ./nginx
  - docker build -t ekpo3/complex-server ./server
  - docker build -t ekpo3/complex-worker ./worker
  - docker push ekpo3/complex-client
  - docker push ekpo3/complex-nginx
  - docker push ekpo3/complex-server
  - docker push ekpo3/complex-worker